
CREATE TABLE MEMB_INFO(
	memb_guid int NOT NULL AUTO_INCREMENT,
	memb___id varchar(10) NOT NULL,
	memb__pwd varchar(20) NOT NULL,
	memb_name varchar(10) NOT NULL,
	sno__numb char(13) NOT NULL,
	post_code char(6) NULL,
	addr_info varchar(50) NULL,
	addr_deta varchar(50) NULL,
	tel__numb varchar(20) NULL,
	phon_numb varchar(15) NULL,
	mail_addr varchar(50) NULL,
	fpas_ques varchar(50) NULL,
	fpas_answ varchar(50) NULL,
	job__code char(2) NULL,
	appl_days datetime NULL,
	modi_days datetime NULL,
	out__days datetime NULL,
	true_days datetime NULL,
  mail_chek char(1) NULL,
	bloc_code char(1) NOT NULL,
	ctl1_code char(1) NOT NULL,
	cspoints int NULL,
	VipType int NULL,
	VipStart datetime NULL,
	VipDays datetime NULL,
	JoinDate varchar(23) NULL
);
